version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: agent_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: agent_orchestration
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: agent_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: agent_orchestration
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017
      - REDIS_URL=redis://redis:6379
      - MCP_ABAP_SERVER_PATH=/app/mcp-servers/sap-abap-adt/dist/index.js
      - ERP_REPORTS_DIRECTORY=/app/reports
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./app:/app
      - ./logs:/logs
      - ./erp_exception_reports:/app/reports
      - ./mcp-servers:/app/mcp-servers

volumes:
  mongodb_data: